In [37]:
import pandas as pd
import numpy as np

In [ ]:
morning_line = pd.read_csv("C:/Users/jwang/Downloads/UCSD Qualifier SIACC Group Registration - Morning Line.csv")
morning_line

,First Name,Last Name,Gender,Division,School,Email,USAA Membership (for SIACC Registration),Draw Weight (for Q3 participants only)
0,Hali,Bergstrom,Female,Barebow,UCSD,berghstrom@gmail.com,NaN,24
1,Daniel,Borrayo,Male,Barebow,UCSD,dborrayo@ucsd.edu,NaN,39
2,Kyle,Canturia,Male,Barebow,UCSD,kcanturia@ucsd.edu,NaN,30
3,Titus,Chan,Male,Barebow,UCSD,tic039@ucsd.edu,NaN,28
4,Jaden,Chan,Female,Barebow,UCSD,jac119@ucsd.edu,NaN,26
5,Hyun-Shin,Cho,Male,Olympic Recurve,UCSD,hyunshincho@gmail.com,NaN,40
6,Diego,Cortez,Male,Barebow,UCSD,Dcortez9838@gmail.com,NaN,32
7,Elizabeth,Dam,Female,Barebow,UCSD,scelizabeth.dxm@gmail.com,NaN,26
8,Andrea,Dinglasan,Female,Fixed Pin,UCSD,andinglasan@ucsd.edu,NaN,35
9,Rick Jaden,Ecijan,Male,Fixed Pin,UCSD,rjecijan@gmail.com,NaN,50
10,Kye,Gibbs,Female,Barebow,UCSD,Khgibbs@ucsd.edu,NaN,34
11,Dani,Gonzalez,Female,Olympic Recurve,UCSD,d7gonzalez@ucsd.edu,NaN,45
12,Justin,Hyon,Male,Olympic Recurve,UCSD,jhyon@ucsd.edu,NaN,55
13,Richenda,Janowitz,Female,Barebow,UCSD,rijanowitz@ucsd.edu,NaN,26
14,Qinghan,Jia,Male,Olympic Recurve,UCSD,qijia@ucsd.edu,NaN,26
15,Hassan Tashfeen,Khan,Male,Barebow,UCSD,hassantk31@gmail.com,NaN,32
16,Andy,Leung,Male,Barebow,UCSD,a7leung@ucsd.edu,NaN,25
17,Unity,Listiak,Female,Barebow,UCSD,Ulistiak@gmail.com,NaN,26
18,Amelie,Lo,Female,Barebow,UCSD,amelie.s.lo109@gmail.com,NaN,26
19,Matthew,Lyons,Male,Fixed Pin,UCSD,matthew.lyons207@gmail.com,NaN,32
20,Mei Lillien,Miyahara,Female,Barebow,UCSD,mmiyahara@ucsd.edu,NaN,26
21,Lindsay Jada,Moreno,Female,Barebow,UCSD,lindsayjmoreno@gmail.com,NaN,24
22,Madelene,Natividad,Female,Barebow,UCSD,mcnatividad@ucsd.edu,NaN,26
23,Jake Shores,Nguyen,Male,Barebow,UCSD,jakeshoresnguyen2006@gmail.com,NaN,26
24,Tatiana,Samokhvalova,Female,Olympic Recurve,UCSD,tanya@samokhvalov.com,NaN,27
25,Haley,Shimabukuro,Female,Olympic Recurve,UCSD,kmshima24@gmail.com,NaN,28
26,Everett,Sprague,Male,Olympic Recurve,UCSD,everett.sprague@gmail.com,NaN,34
27,Marjene,Stiti,Female,Olympic Recurve,UCSD,marjenestiti@gmail.com,NaN,26
28,Jacob,Takesuye,Male,Compound,UCSD,Jtakesuye@ucsd.edu,NaN,55
29,Alexander,Tellez,Male,Compound,UCSD,atellez@ucsd.edu,NaN,55
30,Kade William,Thomas,Male,Barebow,UCSD,onepieceslice@gmail.com,NaN,30
31,Sriveena,Veerapaneni,Female,Compound,UCSD,Sriveena101@gmail.com,NaN,40
32,Lindsey,Vermeulen,Female,Olympic Recurve,UCSD,lvermeulen@ucsd.edu,NaN,30
33,Jared,Wang,Male,Olympic Recurve,UCSD,jaredjcwang@gmail.com,NaN,40
34,Aden,Wong,Male,Olympic Recurve,UCSD,Adenwong111004@gmail.com,NaN,34
35,Elias,Yan,Male,Olympic Recurve,UCSD,ey102262@gmail.com,NaN,34
36,Rebecca,Zhang,Female,Fixed Pin,UCSD,rlz001@ucsd.edu,NaN,35
37,Ivy,Tang,Female,Compound,UCSD,ivtang@ucsd.edu,NaN,35
38,Russell,Wong,Male,Fixed Pin,UCSD,raw020@ucsd.edu,NaN,40

In [39]:
afternoon_line = pd.read_csv("C:/Users/jwang/Downloads/UCSD Qualifier SIACC Group Registration - Afternoon Line.csv")
afternoon_line

,First Name,Last Name,Gender,Division,School,Email,USAA Membership (for SIACC Registration),Draw Weight (for Q3 participants only)
0,Jake,Anwyl,Male,Barebow,UCSD,anwyljh@gmail.com,NaN,26
1,Elvin Liang,Chen,Male,Olympic Recurve,UCSD,elc015@ucsd.edu,NaN,32
2,Conner Weng Kit,Chia,Male,Olympic Recurve,UCSD,cwchia@ucsd.edu,NaN,36
3,Samuel T,Cho,Male,Fixed Pin,UCSD,tad1688@gmail.com,NaN,50
4,Connor Daniel,Cho,Male,Olympic Recurve,UCSD,cocho@ucsd.edu,NaN,26
5,Elizabeth,Dam,Female,Barebow,UCSD,scelizabeth.dxm@gmail.com,NaN,26
6,Kyler Eric,Davis,Male,Olympic Recurve,UCSD,kyler00013@gmail.com,NaN,32
7,Kennedy,Drummond,Female,Barebow,UCSD,kennedydrummond25@gmail.com,NaN,26
8,Diana,Feng,Female,Fixed Pin,UCSD,dxfeng817@gmail.com,NaN,30
9,Dani,Gonzalez,Female,Compound,UCSD,d7gonzalez@ucsd.edu,NaN,50
10,Justin,Hyon,Male,Fixed Pin,UCSD,jhyon@ucsd.edu,NaN,40
11,Qinghan,Jia,Male,Olympic Recurve,UCSD,qijia@ucsd.edu,NaN,26
12,Isaiah Wallace,Jimenez,Male,Barebow,UCSD,isaiah.jimenez444@gmail.com,NaN,30
13,Hassan Tashfeen,Khan,Male,Barebow,UCSD,hassantk31@gmail.com,NaN,32
14,Ka Hei,Lai,Male,Olympic Recurve,UCSD,hugolaiatus@gmail.com,NaN,34
15,Aayan,Lakhani,Male,Olympic Recurve,UCSD,aalakhani@ucsd.edu,NaN,26
16,Jayden,Lee,Male,Barebow,UCSD,jdl016@ucsd.edu,NaN,26
17,Tanya Diana,Lee,Female,Fixed Pin,UCSD,tal034@ucsd.edu,NaN,35
18,Devin,Luu,Male,Barebow,UCSD,DevinL1000@gmail.com,NaN,26
19,Matthew,Lyons,Male,Fixed Pin,UCSD,matthew.lyons207@gmail.com,NaN,32
20,Hung,Nguyen,Male,Barebow,UCSD,hun007@ucsd.edu,NaN,26
21,Tony Ngoc,Nguyen,Male,Barebow,UCSD,tien.ngo1106@gmail.com,NaN,32
22,Jake Shores,Nguyen,Male,Barebow,UCSD,jakeshoresnguyen2006@gmail.com,NaN,26
23,Jeffrey,Pan,Male,Barebow,UCSD,Jep040@ucsd.edu,NaN,34
24,Edwin,Perez Pulido,Male,Compound,UCSD,eperezpulido@ucsd.edu,NaN,55
25,Bryan,Perez,Male,Fixed Pin,UCSD,Perezpr0921@gmail.com,NaN,52
26,Pranaad,Rane,Male,Fixed Pin,UCSD,pranaadrane33@gmail.com,NaN,50
27,Alexander,Tellez,Male,Compound,UCSD,atellez@ucsd.edu,NaN,55
28,Lindsey,Vermeulen,Female,Compound,UCSD,lvermeulen@ucsd.edu,NaN,40
29,Florence Ziyue,Wang,Female,Barebow,UCSD,mew057@ucsd.edu,NaN,26
30,Shiran,Wang,Female,Barebow,UCSD,shw168@ucsd.edu,NaN,26
31,Russell,Wong,Male,Fixed Pin,UCSD,raw020@ucsd.edu,NaN,40
32,Gordon,Yang,Male,Olympic Recurve,UCSD,gcyang@ucsd.edu,NaN,32
33,Tuo,Zheng,Male,Fixed Pin,UCSD,tzheng846@gmail.com,NaN,50
34,Arianna,Zunich,Female,Barebow,UCSD,ariannazunich@gmail.com,NaN,24

In [62]:
import pandas as pd

def get_unique_people(morning_line: pd.DataFrame, afternoon_line: pd.DataFrame) -> pd.DataFrame:
    # Combine both DataFrames
    combined = pd.concat([morning_line, afternoon_line], ignore_index=True)

    # Define identifying columns (adjust if needed)
    id_cols = ['First Name', 'Last Name', 'Email']

    # Drop duplicates based on identifying columns
    unique_people = combined.drop_duplicates(subset=id_cols, keep='first')

    return unique_people

original_list = list(get_unique_people(morning_line, afternoon_line)["First Name"].sort_values(ascending=True))

In [63]:
original_list

['Aayan',
 'Aden',
 'Alexander',
 'Amelie',
 'Andrea',
 'Andy',
 'Arianna',
 'Bryan',
 'Conner Weng Kit',
 'Connor Daniel',
 'Dani',
 'Daniel',
 'Devin',
 'Diana',
 'Diego',
 'Edwin',
 'Elias',
 'Elizabeth',
 'Elvin Liang',
 'Everett',
 'Florence Ziyue',
 'Gordon',
 'Haley',
 'Hali',
 'Hassan Tashfeen',
 'Hung',
 'Hyun-Shin',
 'Isaiah Wallace',
 'Ivy',
 'Jacob ',
 'Jaden',
 'Jake',
 'Jake Shores',
 'Jared',
 'Jayden',
 'Jeffrey',
 'Justin',
 'Ka Hei',
 'Kade William',
 'Kennedy ',
 'Kye',
 'Kyle',
 'Kyler Eric',
 'Lindsay Jada',
 'Lindsey',
 'Lindsey ',
 'Madelene',
 'Marjene',
 'Matthew',
 'Mei Lillien',
 'Pranaad',
 'Qinghan',
 'Rebecca',
 'Richenda',
 'Rick Jaden',
 'Russell',
 'Samuel T',
 'Shiran',
 'Sriveena',
 'Tanya Diana',
 'Tatiana',
 'Titus',
 'Tony Ngoc',
 'Tuo',
 'Unity']

65