In [4]:
# Initialize Otter
import otter
grader = otter.Notebook("project.ipynb")

c:\Users\jwang\Miniforge3\envs\dsc80\Lib\site-packages\otter\export\__init__.py:6: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

# Project 1 – Gradebook 💯

## DSC 80, Fall 2025

### Checkpoint Due Date: Thursday, October 9th (Questions 1-7)
### Due Date: Thursday, October 16th

## Instructions

Welcome to Project 1! Be sure to read the instructions below carefully to understand how projects differ from labs.

### Working on the Project

This Jupyter Notebook contains the statements of the problems and provides code and Markdown cells to display your answers to the problems.

* Like the lab, your coding work will be developed in the accompanying `project.py` file, that will be imported into the current notebook. This code will be autograded.
* There is no manually-graded component to Project 1, so the only thing you will ever submit is `project.py`.
* **For the Checkpoint, which is required, you only need to turn in a `project.py` containing solutions for Questions 1-7!**
    - The "Project 1 Checkpoint" autograder on Gradescope does not thoroughly check your code – it only runs the public tests on Questions 1-7 to make sure that you have completed them. There are no hidden tests for the checkpoint, and you will see your score upon submission. 
    - When you submit the final version of the project, however, we will use hidden tests to check your answers more thoroughly.
    - Note that this means you will ultimately have to submit the project twice – once to the "Project 1 Checkpoint" autograder (Questions 1-7 only), and once to the "Project 1" autograder (once you're fully done).
- **Do not change the function names in `project.py` file!** The functions in `project.py` are how your assignment is graded, and they are graded by their name. If you changed something you weren't supposed to, you can find the original code in the [course GitHub repository](https://github.com/dsc-courses/dsc80-2025-fa).
- **To ensure that all of your work to be submitted is in `project.py`, we've included a script named `project-validation.py` in the project folder. You shouldn't edit it, but instead, you should call it from the command line (e.g. the Terminal) to test your work.** More details on its usage are given at the bottom of this notebook.
- You are encouraged to write your own additional helper functions to solve the project, as long as they also end up in `project.py`.

### Working with a Partner

You may work together on projects (and projects only!) with a partner. If you work with a partner, you are both required to actively contribute to all parts of the project. You must both be working on the assignment at the same time together, either physically or virtually on a Zoom call. You are encouraged to follow the pair programming model, in which you work on just a single computer and alternate who writes the code and who thinks about the problems at a high level.

In particular, you **cannot** split up the project and each work on separate parts independently.

Note that if you do work with a partner, you and your partner must submit the Checkpoint together and the whole project together. See [here](https://dsc80.com/syllabus.html#projects) for more details.

In [5]:
%load_ext autoreload
%autoreload 2

In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

import plotly.express as px
import plotly.io as pio
pio.renderers.default = "plotly_mimetype+notebook"

In [7]:
from project import *

## About the Assignment

In this project, you'll work with the gradebook for CSD 18, a fictional data science course with 535 students co-taught by Professors Yutian and Dylan. You'll help Professors Yutian and Dylan compute the total course grade for every student in their course and analyze their students' performances throughout the quarter.

---

### Navigating the Project

Click on the links below to navigate to different parts of the project. Note that Part 1 – that is, Questions 1, 2, 3, 4, 5, 6, and 7 – constitutes your Checkpoint submission.

- [Part 1: Initial Calculations 🔢](#part1)
    - [Question 1 ](#Question-1-(Checkpoint-Question))
    - [Question 2 ](#Question-2-(Checkpoint-Question))
    - [Question 3 ](#Question-3-(Checkpoint-Question))
    - [Question 4 ](#Question-4-(Checkpoint-Question))
    - [Question 5 ](#Question-5-(Checkpoint-Question))
    - [Question 6 ](#Question-6-(Checkpoint-Question))
    - [Question 7 ](#Question-7-(Checkpoint-Question))
- [Part 2: Redemption 🙏](#part2)
    - [Question 8](#Question-8)
    - [Question 9](#Question-9)
    - [Question 10](#Question-10)
- [Part 3: Analysis 🧠](#part3)
    - [Question 11](#Question-11)
    - [Question 12](#Question-12)
    - [Question 13](#Question-13)

<!--     - [✅ Question 1 (Checkpoint Question)](#Question-1-(Checkpoint-Question))
    - [✅ Question 2 (Checkpoint Question)](#Question-2-(Checkpoint-Question))
    - [✅ Question 3 (Checkpoint Question)](#Question-3-(Checkpoint-Question))
    - [✅ Question 4 (Checkpoint Question)](#Question-4-(Checkpoint-Question))
    - [✅ Question 5 (Checkpoint Question)](#Question-5-(Checkpoint-Question))
    - [✅ Question 6 (Checkpoint Question)](#Question-6-(Checkpoint-Question))
    - [✅ Question 7 (Checkpoint Question)](#Question-7-(Checkpoint-Question)) -->
---

### The Syllabus

Professor Yutian has taught this course several times, so the instructors decide to use her syllabus at the start of the quarter. (Note that this syllabus is **not** the same as the course syllabus for DSC 80 in Fall 2025)

* **Lab assignments (20% total)**
    - Each lab is worth the same amount, regardless of each lab's raw point total.
    - The lowest lab is dropped.
    - Each lab may be revised for up to (and including) one week after the deadline for a 10% penalty, for up to (and including) two weeks after the deadline for a 30% penalty, and beyond that for a 60% penalty. Such revisions are reflected in the `'Lateness'` columns in the gradebook.
    - Labs also have a two hour grace period that needs to be factored in before assigning late penalties.
    - Note that lateness penalties are not assessed for any other type of assignment – that is, students can submit projects, checkpoints, and discussions late without penalty.
* **Projects (30% total)** 
    - Each project consists of an autograded portion, and **possibly** a free response portion.
    - The total points for a single project consist of the sum of the raw score of the two portions.
    - Each project is worth the same amount, regardless of each project's raw point total.
* **Checkpoints (2.5% total)**
    - Each project checkpoint is worth the same amount, regardless of each project checkpoint's raw point total.
* **Discussions (2.5% total)**
    - Each discussion is worth the same amount, regardless of each discussion's raw point total.
* **Midterm Exam (15%)**
* **Final Exam (30%)**

You will need to refer to this syllabus repeatedly throughout the project, and several questions will link you back to it.

---

### Generalization

Your code only needs to work for courses that follow the syllabus above. That is, you may assume that the DataFrame `grades` looks **like** the given one in `data/grades.csv`.

However, your code should work regardless of:
- The numbers of labs, projects, discussions, and checkpoints in the course.
- The number of students in the course.

For instance, if CSD 18 is taught in a different quarter with more labs, fewer projects, and fewer students, your code should still work on a `grades.csv` from that quarter.

You may assume the course components and the naming conventions are as given in `grades.csv`, and you may assume that the course has no more than 99 of any type of assignment.

---

### Putting Everything Together

Here are a few remarks and tips for approaching Project 1, and projects more generally:

1. If you are having trouble figuring out what a question is asking you to do, look at the big picture and try to understand what the current step is doing to contribute to this big picture. This may clarify what's being asked!
1. These questions intentionally build off of each other and the final result matters! In fact, you can "get a question correct," but only receive partial credit for it because a previous answer was wrong.
    - Credit for a question will typically receive partial credit based on *how close* your answer is to correct (as well as some credit for a solution in the correct form). 
    - You should try to assess your answer to each question based on what you understand of the data. This might involve writing extensive code (that isn't turned in) just to check your work! Suggestions on checking your work are given in the assignment, but you should also think of your own ways of checking your work.
    - As you do this project, think about the data from the perspective of the student (which should be easy to do, since you've used Gradescope before!)
1. To test the correctness of your answers:
     - Once you have implemented a particular function in `project.py`, you should test out your function in the notebook. In particular, you should inspect/analyze the output to assess its correctness.
    - Run your functions on the main dataset (`grades`, and later `grades_combined` and `grades_analysis`) and ask yourself if the output *looks correct.*
    - Run your functions on very small datasets (e.g. 1-5 row DataFrames that you construct by hand), calculate the expected output by hand, and see if the function output matches (this *is* unit-testing your code with data).
    * Run your functions on (large and small) samples of the dataset `grades`. Does your code break, or does it still run as expected?

Run the cell below to load in the aforementioned `grades` dataset.

In [8]:
grades_fp = Path('data') / 'grades.csv'
grades = pd.read_csv(grades_fp)
grades.head()

,PID,College,Level,Section,lab01,lab01 - Max Points,lab01 - Lateness (H:M:S),lab02,lab02 - Max Points,lab02 - Lateness (H:M:S),...,discussion07 - Lateness (H:M:S),discussion08,discussion08 - Max Points,discussion08 - Lateness (H:M:S),discussion09,discussion09 - Max Points,discussion09 - Lateness (H:M:S),discussion10,discussion10 - Max Points,discussion10 - Lateness (H:M:S)
0,A99706914,ERC,JR,A22,99.735279,100.0,00:00:00,84.990171,100.0,00:00:00,...,00:00:00,8.895294,10,00:00:00,10.000000,10,780:01:28,10.000000,10,00:00:00
1,A99237411,Eighth,JR,A29,98.829476,100.0,00:00:00,50.784231,100.0,00:00:00,...,669:12:21,9.022407,10,00:00:00,9.020283,10,00:00:00,9.437368,10,00:00:00
2,A99690544,Revelle,SR,A12,86.513369,100.0,00:00:00,47.802820,100.0,00:00:00,...,00:00:00,3.030538,10,00:04:51,7.613698,10,00:00:00,9.624617,10,00:00:00
3,A99427381,Seventh,JR,A14,100.000000,100.0,00:00:00,100.000000,100.0,00:00:00,...,00:00:00,10.000000,10,00:00:00,9.249126,10,00:00:00,10.000000,10,00:00:00
4,A99489712,Sixth,JR,A24,66.506974,100.0,00:00:00,33.422412,100.0,00:00:00,...,00:00:00,4.439606,10,00:00:00,4.485291,10,00:00:00,6.282712,10,00:00:00

***Tip***: The `grades` DataFrame has 101 columns, and you can't see them all right now. To get a feel for what all of the columns represent, you might consider opening `grades.csv` with a spreadsheet application, like Google Sheets or Excel.

<a name='part1'></a>

## Part 1: Initial Calculations 🔢

([return to the outline](#Navigating-the-Project))

In Part 1, you'll compute students' letter grades in CSD 18 using [the syllabus](#The-Syllabus) provided above. As you'll see, this requires many steps. Let's get started!

<!-- ### ✅ Question 1 (Checkpoint Question) -->
### Question 1 


<a name='Question-1-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

Complete the implementation of the function `get_assignment_names`, which takes in a DataFrame like `grades` and returns a dictionary with the following structure:
- The keys are the general areas of [the syllabus](#The-Syllabus): `'lab'`, `'project'`, `'midterm'`, `'final'`, `'disc'`, and `'checkpoint'`.
- The values are **lists** that contain all the assignment names of that type. For example, the lab assignments all have names of the form `'labXX'` where `XX` is a zero-padded two digit number. If the class has 5 labs, the returned dictionary's value for the `'lab'` key should be `['lab01', 'lab02', 'lab03', 'lab04', 'lab05']`.

***Notes***: 
- Some of the column names in the DataFrame contain the assignment name in the zero-padded fashion requested; you should use this to your advantange when building the dictionary.
- The point of this question is to familiarize you with the names of the columns in `grades`. Try to reuse your `get_assignment_names` function in future questions – if you find yourself never using it again, you may be redoing work unnecessarily.

In [9]:
def get_assignment_names(dFrame):
    dct = {'lab': [], 'project': [], 'midterm': [], 'final': [], 'disc': [], 'checkpoint': []}
    labs = []
    projects = []
    midterms = []
    final = []
    discs = []
    checkpoints = []

    for i in dFrame.columns:
        if i.startswith('lab') and i[-1].isnumeric():
            labs.append(i)
        if i.startswith('project') and i[-1].isnumeric() and i.find('checkpoint') == -1:
            projects.append(i)
        if i.startswith('Midterm') and i.find('-') == -1:
            midterms.append(i)
        if i.startswith('Final') and i.find('-') == -1:
            final.append(i)
        if i.startswith('discussion') and i[-1].isnumeric():
            discs.append(i)
        if i.find('checkpoint') != -1 and i.find('-') == -1:
            checkpoints.append(i)
    
    dct.update({'lab': labs})
    dct.update({'project': projects})
    dct.update({'midterm': midterms})
    dct.update({'final': final})
    dct.update({'disc': discs})
    dct.update({'checkpoint': checkpoints})
    return dct

In [10]:
get_assignment_names(grades)

{'lab': ['lab01',
  'lab02',
  'lab03',
  'lab04',
  'lab05',
  'lab06',
  'lab07',
  'lab08',
  'lab09'],
 'project': ['project01', 'project02', 'project03', 'project04', 'project05'],
 'midterm': ['Midterm'],
 'final': ['Final'],
 'disc': ['discussion01',
  'discussion02',
  'discussion03',
  'discussion04',
  'discussion05',
  'discussion06',
  'discussion07',
  'discussion08',
  'discussion09',
  'discussion10'],
 'checkpoint': ['project02_checkpoint01',
  'project02_checkpoint02',
  'project03_checkpoint01']}

In [11]:
grader.check("q1")

q1 results: All test cases passed!

Now you're ready to compute each student's overall grade on the first type of assignment – projects.

<!-- ### ✅ Question 2 (Checkpoint Question) -->
### Question 2


<a name='Question-2-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

Complete the implementation of the function `projects_total`, which takes in a DataFrame like `grades` and returns a Series containing the total project grade for each student for the entire quarter, according to [the syllabus](#The-Syllabus). The output Series should contain values between 0 and 1.

***Notes***:

- If a student didn't turn in a particular project, what should their grade for it be? 
- Some projects have free response components that you need to account for when calculating the total points earned by a student and the max points possible for that project.
    - For instance, let's say Tiffany earned 82 points on the autograded portion of Project 1 and 13 points on the free response portion. This means that her overall Project 1 grade should be:
    $$
        \text{Project 1 Grade} = \frac{82+13}{85+15} = 0.95
    $$
- Per [the syllabus](#The-Syllabus), students may submit projects (and checkpoints and discussions) late without penalty.
- Do not include scores on checkpoint assignments in your calculations.
- To check your work, try:
    1. Calculating the total project scores for a few types of students by hand.
    2. Calculating summary statistics for the whole class' performance on a few projects in particular and ensuring the results seem reasonable.

In [12]:
def projects_total(grades):
    grades = grades.fillna(0)

    project_grades = []
    frq_grades = []
    max_project_grades = []
    max_frq_grades = []
    for i in grades.columns:
        if i.startswith('project') and i[-1].isnumeric() and i.find('checkpoint') == -1:
            project_grades.append(i)
        if i.startswith('project') and i.find('free') != -1 and i.find('-') == -1:
            frq_grades.append(i)
        if i.startswith('project') and i.find('Max') != -1 and i.find('checkpoint') == -1 and i.find('free') == -1:
            max_project_grades.append(i)
        if i.startswith('project') and i.find('Max') != -1 and i.find('checkpoint') == -1 and i.find('free') != -1:
            max_frq_grades.append(i)

    frq_nums = []
    for i in frq_grades:
        frq_nums.append(i[7:9])

    proj_final_grades = pd.Series()

    frq_index = 0
    for i in range(len(project_grades)):
        if project_grades[i][7:9] in frq_nums:
            proj_final_grades[project_grades[i]] = ((grades.get(project_grades[i]) + grades.get(frq_grades[frq_index])) / (grades.get(max_project_grades[i]) + grades.get(max_frq_grades[frq_index])))
            frq_index += 1
        else:
            proj_final_grades[project_grades[i]] = (grades.get(project_grades[i]) / grades.get(max_project_grades[i]))
    
    sums = np.zeros(len(proj_final_grades.iloc[0]))
    for i in proj_final_grades:
        for j in range(len(i)):
            sums[j] += i[j]
    return pd.Series(sums / len(proj_final_grades), index = grades.index)

In [13]:
projects_total(grades)

0      0.916234
1      0.765932
2      0.681279
3      0.962581
4      0.737446
         ...
530    0.949434
531    0.866795
532    0.862050
533    0.813468
534    0.939433
Length: 535, dtype: float64

In [14]:
grader.check("q2")

q2 results: All test cases passed!

Now that projects are out of the way, you need to clean and process the lab grades. This will involve a bit more work than was necessary for projects. Specifically, you'll:
- identify late submissions (Question 3), 
- compute normalized scores for each lab assignment, factoring in late penalties (Question 4), and 
- drop the lowest lab grade and compute a total lab score for each student (Question 5).

<!-- ### ✅ Question 3 (Checkpoint Question) -->
### Question 3 


<a name='Question-3-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

Recall, per [the syllabus](#The-Syllabus), labs are the only assignment category for which late penalties are enforced:

>  Each lab may be revised for up to (and including) one week after the deadline for a 10% penalty, for up to (and including) two weeks after the deadline for a 30% penalty, and beyond that for a 60% penalty. Such revisions are reflected in the `'Lateness'` columns in the gradebook.

For labs, students have a **two hour grace period** after the deadline during which their submissions are counted as on time. The grace period only applies to the original deadline – for instance, if a student submits one week and one hour late, their submission falls into the "up to (and including) two weeks after the deadline" category and they are assessed a 30% penalty.

Your job is to adjust lab grades to penalize **truly** late submissions, factoring in the grace period. To adjust a student's grade, multiply their lab score by `1` (on time, factoring in the grace period), `0.9`, `0.7`, or `0.4`. We'll call these four numbers – `1`, `0.9`, `0.7`, and `0.4` – "lateness multipliers." 

Complete the implementation of the function `lateness_penalty`, which takes in a Series containing information on how late each student turned in a particular lab, such as `grades['lab01 - Lateness (H:M:S)']`, and returns a Series containing each student's lateness multiplier for that lab. The only possible values in the returned Series should be `1.0`, `0.9`, `0.7`, and `0.4`.

**Don't forget to factor in the grace period!** Remember, we will only be enforcing late penalties for labs, not for any other assignment category.

**Note**: There is no grace period for real Gradescope!! Make sure you submit your assignments on time.

In [15]:
def lateness_penalty(series):
    penalties = []
    times_list = []
    times_secs = []
    for i in series:
        times_list.append(i.split(":"))
    for i in times_list:
        times_secs.append(int(i[0]) * 3600 + int(i[1]) * 60 + int(i[2]))
    for i in times_secs:
        if int(i) > 1209600:
            penalties.append(0.4)
        elif int(i) > 604800:
            penalties.append(0.7)
        elif int(i) > 7200:
            penalties.append(0.9) 
        else:
            penalties.append(1.0)
    return pd.Series(penalties, index=series.index)

In [16]:
print(lateness_penalty(grades['lab01 - Lateness (H:M:S)']))
print(lateness_penalty(grades['lab02 - Lateness (H:M:S)']))
print(lateness_penalty(grades['lab03 - Lateness (H:M:S)']))
print(lateness_penalty(grades['lab04 - Lateness (H:M:S)']))
print(lateness_penalty(grades['lab05 - Lateness (H:M:S)']))

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
530    0.9
531    1.0
532    1.0
533    1.0
534    1.0
Length: 535, dtype: float64
0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
530    1.0
531    1.0
532    1.0
533    1.0
534    1.0
Length: 535, dtype: float64
0      0.7
1      1.0
2      1.0
3      1.0
4      1.0
      ...
530    1.0
531    1.0
532    1.0
533    1.0
534    1.0
Length: 535, dtype: float64
0      1.0
1      1.0
2      1.0
3      1.0
4      0.9
      ...
530    0.9
531    0.9
532    1.0
533    1.0
534    1.0
Length: 535, dtype: float64
0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
530    1.0
531    1.0
532    1.0
533    1.0
534    1.0
Length: 535, dtype: float64

In [17]:
grader.check("q3")

q3 results: All test cases passed!

<!-- ### ✅ Question 4 (Checkpoint Question) -->
### Question 4 

<a name='Question-4-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

Complete the implementation of the function `process_labs`, which takes in a DataFrame like `grades` and returns a DataFrame of processed lab scores. The returned DataFrame should:
* have the same index as `grades`,
* have one column for each lab assignment (e.g. `'lab01'`, `'lab02'`,..., `'lab09'`),
* have values representing the final score for each lab assignment, adjusted for lateness and **normalized** to a score between 0 and 1.

Remember to correctly handle the case where a student _doesn't_ turn in a lab.

In [18]:
def process_labs(grades):
    grades = grades.fillna(0)
    idx = grades.index
    lab_df = pd.DataFrame(index=idx, columns=get_assignment_names(grades)["lab"])
    lateness = []
    max_points_cols = []
    max_points = []
    for i in grades.columns:
        if i.startswith('lab') and i.find('Max') != -1:
            max_points_cols.append(i)
    for i in max_points_cols:
        max_points.append(grades[i])
    for i in lab_df.columns + " - Lateness (H:M:S)":
        lateness.append(lateness_penalty(grades[i]))
    scores = []
    for i in lab_df.columns:
        scores.append(grades[i])
    with_lateness = []
    for i in range(len(lab_df.columns)):
        with_lateness.append(lateness[i] * scores[i])
    for i in range(len(with_lateness)):
        lab_df[lab_df.columns[i]] = with_lateness[i] / max_points[i]
    return lab_df

In [19]:
process_labs(grades)

,lab01,lab02,lab03,lab04,lab05,lab06,lab07,lab08,lab09
0,0.997353,0.849902,0.637744,1.000000,1.000000,0.994518,0.389141,0.887917,0.874913
1,0.988295,0.507842,0.714477,0.783672,1.000000,0.393887,0.914061,0.944378,0.902977
2,0.865134,0.478028,0.433667,0.738875,0.927838,0.345076,0.734070,0.718204,0.757840
3,1.000000,1.000000,0.925903,0.950614,0.891614,0.688403,0.985371,0.963307,0.777880
4,0.665070,0.334224,0.706932,0.747915,0.659720,0.731345,0.607859,0.370186,1.000000
...,...,...,...,...,...,...,...,...,...
530,0.900000,0.820228,1.000000,0.792935,1.000000,0.284106,0.770281,0.931245,1.000000
531,1.000000,0.874981,0.809945,0.592866,0.987597,0.759688,0.856178,0.849694,0.582645
532,0.886566,0.903260,1.000000,1.000000,0.941425,0.768909,0.967282,0.877898,1.000000
533,0.837997,0.856369,0.909363,0.955287,0.737854,0.382781,0.769093,0.947450,0.867373
534,0.883893,0.730452,0.944795,0.819100,0.890968,0.858277,0.989410,0.807974,0.663745

In [20]:
grader.check("q4")

q4 results: All test cases passed!

<!-- ### ✅ Question 5 (Checkpoint Question) -->
### Question 5 

<a name='Question-5-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

Complete the implementation of the function `lab_total`, which takes in a DataFrame returned by `process_labs` – that is, a DataFrame that contains each student's score on each lab after lateness penalties – and returns a Series containing the total lab grade for each student according to [the syllabus](#The-Syllabus) (i.e. with the lowest lab dropped). All values in the returned Series should be proportions between 0 and 1. 

For example, if CSD 18 only has 3 labs, and Aritra received lab scores of 20%, 90%, and 100% after lateness penalties, then your output Series should contain the value `0.95` for Aritra. This is because we drop the lowest score, and then compute the average of just 90% and 100%, which is 95%, or 0.95 as a proportion.

In [21]:
def lab_total(df):
    lab_grades = []
    for i in range(df.shape[0]):
        lab_grades.append((sum(list(df.iloc[i])) - (min(df.iloc[i]))) / (len(list(df.iloc[i])) - 1))
    return pd.Series(lab_grades, index = df.index)

In [22]:
lab_total(process_labs(grades))

0      0.905293
1      0.844463
2      0.706707
3      0.936836
4      0.686128
         ...
530    0.901836
531    0.841369
532    0.947054
533    0.860098
534    0.865609
Length: 535, dtype: float64

In [23]:
grader.check("q5")

q5 results: All test cases passed!

Now that projects and labs are processed, we're almost ready to compute the letter grade of each student in CSD 18.

### Question 6
<!-- ### ✅ Question 6 (Checkpoint Question) -->

<a name='Question-6-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

First, you need to compute each student's course grade, which results from adding their total grades in each course component according to the weights given in [the syllabus](#The-Syllabus).

Complete the implementation of the function `total_points`, which takes in a DataFrame like `grades` and returns a Series containing each student's course grade. **Course grades should be proportions between 0 and 1.**

***Notes***: 

- Don't repeat yourself when computing the checkpoint and discussion portions of the course.
- Remember, only the lab portion of the course accounts for late assignments; you may assume all assignments in other portions are turned in without penalty.
- Do the work by hand for a few students to check your code!

In [24]:
def total_points(df):
    df = df.fillna(0)
    labs = lab_total(process_labs(df)) * 0.2
    projects = projects_total(df) * 0.3

    checkpoints_names = get_assignment_names(df)["checkpoint"]
    checkpoints_max = []
    for i in df.columns:
        if i.find("Max") != -1 and i.find("checkpoint") != -1:
            checkpoints_max.append(i)
    checkpoints_as_percent = []
    for i in range(len(checkpoints_names)):
        checkpoints_as_percent.append(df[checkpoints_names[i]] / df[checkpoints_max[i]])
    all_checkpoints = np.zeros(len(df))
    for i in checkpoints_as_percent:
        all_checkpoints += i
    checkpoints = all_checkpoints / len(checkpoints_names) * 0.025

    discussion_names = get_assignment_names(df)["disc"]
    disc_max = []
    for i in df.columns:
        if (i.find("Max") != -1) and (i.find("discussion") != -1):
            disc_max.append(i)
    disc_as_percent = []
    for i in range(len(discussion_names)):
        disc_as_percent.append(df[discussion_names[i]] / df[disc_max[i]])
    all_disc = np.zeros(len(df))
    for i in disc_as_percent:
        all_disc += i
    disc = all_disc / len(discussion_names) * 0.025

    midterms = df["Midterm"] / df["Midterm - Max Points"] * 0.15
    finals = df["Final"] / df["Final - Max Points"] * 0.3
    return labs + projects + checkpoints + disc + midterms + finals

In [25]:
total_points(grades)

0      0.902389
1      0.816924
2      0.759308
3      0.908499
4      0.674545
         ...
530    0.864016
531    0.765390
532    0.859673
533    0.866263
534    0.896365
Length: 535, dtype: float64

In [26]:
grader.check("q6")

q6 results: All test cases passed!

<!-- ### ✅ Question 7 (Checkpoint Question) -->
### Question 7

<a name='Question-7-(Checkpoint-Question)'></a>

([return to the outline](#Navigating-the-Project))

How well did the students in CSD 18 do?

#### `final_grades`

Complete the implementation of the function `final_grades`, which takes in a Series of final course grades (as computed by `total_points` in Question 6) and returns a Series of letter grades as determined by the following cutoffs:

| Letter Grade | Cutoff |
|:--- | --- |
| A | grade >= 0.9 |
| B | 0.8 <= grade < 0.9 |
| C | 0.7 <= grade < 0.8 |
| D | 0.6 <= grade < 0.7 |
| F | grade < 0.6 |

***Note***: These cutoffs do not have pluses or minuses. **Do not round** anyone's course grade when determining their letter grade.

<br>

#### `letter_proportions`

Complete the implementation of the function `letter_proportions`, which takes in a Series of final course grades (as computed by `total_points` in Question 6) and returns a Series containing the proportion of the class that received each letter grade. For instance, this Series might tell us that the proportion of the class receiving B's was 0.45, A's was 0.33, C's was 0.16, D's was 0.05, and F's was 0.01 (though these are made up numbers). The index of this Series should be letters, and the **values should be sorted in decreasing order**.

***Notes***: 

- The values in your returned Series should add up to exactly `1.0`. If you are getting something close such as `0.99999`, that means there is an issue with your code in a function you implemented earlier.
- **Do not round**.

In [27]:
def final_grades(series): 
    grades = []
    for grade in series:
        if grade >= 0.9:
            grades.append("A")
        elif 0.8 <= grade < 0.9:
            grades.append("B")
        elif 0.7 <= grade < 0.8:
            grades.append("C")
        elif 0.6 <= grade < 0.7:
            grades.append("D")
        elif grade < 0.6:
            grades.append("F")
    return pd.Series(grades)

In [28]:
def letter_proportions(series):
    letter_grades = {'A': 0, "B": 0, "C": 0, "D": 0, "F": 0}
    for grade in series:
        if grade >= 0.9:
            letter_grades["A"] += 1
        elif 0.8 <= grade < 0.9:
            letter_grades["B"] += 1
        elif 0.7 <= grade < 0.8:
            letter_grades["C"] += 1
        elif 0.6 <= grade < 0.7:
            letter_grades["D"] += 1
        elif grade < 0.6:
            letter_grades["F"] += 1
    letter_grades["A"] /= len(series)
    letter_grades["B"] /= len(series)
    letter_grades["C"] /= len(series)
    letter_grades["D"] /= len(series)
    letter_grades["F"] /= len(series)
    return pd.Series(letter_grades).sort_values(ascending=False)

In [29]:
print(final_grades(pd.Series([0.92, 0.81, 0.41])))
letter_proportions(total_points(grades))

0    A
1    B
2    F
dtype: object

B    0.499065
C    0.228037
A    0.211215
D    0.031776
F    0.029907
dtype: float64

In [30]:
grader.check("q7")

q7 results: All test cases passed!

<a name='part2'></a>

## Part 2: Redemption 🙏

([return to the outline](#Navigating-the-Project))

The syllabus we've used so far was put together by Professor Yutian, who has taught CSD 18 for several iterations. This was Professor Dylan's first time teaching CSD 18, and towards the end of the quarter he proposed a new idea to reward students for showing an improvement in their understanding of the earlier ideas in the course on the final exam. Specifically, here's what he proposed:

- The instructors will identify the questions on the final exam that contain content that was also covered on the midterm exam. Call these "redemption questions."
- For each student, compute their "raw redemption score", which is the proportion of points available on redemption questions that they earned. If they did not take the final exam, their raw redemption score is 0.
- Convert the class' raw redemption scores to z-scores, i.e. to standard units.
- Convert the class' original midterm exam grades, as proportions, to z-scores.
- If a student's raw redemption z-score is higher than their original midterm exam z-score, replace their original midterm exam score with one that has a z-score equal to their raw redemption z-score. This is done by converting their raw redemption z-score back to a midterm grade proportion using the standard deviation and mean of the midterm exam.
- If not, leave their original midterm exam score as-is. **Note that this policy can only increase a student's midterm exam score (and, hence, their total course grade), not decrease!**

As a refresher from [DSC 10](https://dsc-courses.github.io/dsc10-2022-fa/resources/lectures/lec21/lec21.html#Standard-units), to convert a sequence of numbers to z-scores, or standard units, we use the following formula:

$$z(x_i) = \frac{x_i - \text{mean of } x}{\text{SD of }x}$$

To illustrate this redemption policy, let's look at a concrete example.

- Suppose the final exam was worth 80 points. 55 of these points came from Questions 2, 4, 6, 8, and 9, which were the redemption questions. The class' mean score on just the redemption questions was 0.8, with a standard deviation of 0.15.
- Suppose the midterm exam was worth 70 points. The class' mean score on the midterm exam was 0.6, with a standard deviation of 0.25.
- Jasmine, a student in the course, earned a $\frac{74}{80}$ on the final exam, including a $\frac{51}{55}$ on the redemption questions, and a $\frac{53}{70}$ on the midterm exam. Then:
    - Her raw redemption score is $\frac{51}{55}$, and her redemption z-score is $\frac{\frac{51}{55} - 0.8}{0.15} \approx 0.8485$.
    - Her midterm z-score is $\frac{\frac{53}{70} - 0.6}{0.25} \approx 0.6286$.
    - Since her redemption z-score, $0.8485$, is greater than her midterm z-score, $0.6286$, her midterm exam score of $\frac{53}{70} \approx 0.7571$ will be replaced with:
    
    $$\text{Jasmine's redemption z-score} \cdot \text{class' midterm SD} + \text{class' midterm mean} \approx 0.8485 \cdot 0.25 + 0.6 = \boxed{0.8121}$$

Now, your job will be to implement this redemption policy and recompute each student's total course points. Before proceeding, you should think about _why_ Professor Dylan has chosen to implement the redemption policy in terms of z-scores, rather than in terms of raw scores.

A few more things to consider:
- We rounded in the example above, but you should not round at any point in this part.
- After redemption, midterm exam grades should be capped at 1 (as a proportion), i.e. 100%.

It turns out that CSVs like `grades.csv` don't actually contain all of the information you'll need to implement this policy. For instance, `grades` only contains each student's total final exam grade, but not the number of points they earned on each question.

That information will come from another source. For the students whose grades are in `grades`, the CSV `data/final_exam_breakdown.csv` contains the number of points each student earned on each question of CSD 18's final exam. Run the cell below to load this CSV in as a DataFrame named `final_breakdown`.

In [31]:
final_breakdown_fp = Path('data') / 'final_exam_breakdown.csv'
final_breakdown = pd.read_csv(final_breakdown_fp)
final_breakdown.head()

,PID,Question 1 (5.0 pts),Question 2 (6.0 pts),Question 3 (8.0 pts),Question 4 (6.0 pts),Question 5 (10.0 pts),Question 6 (6.0 pts),Question 7 (10.0 pts),Question 8 (6.0 pts),Question 9 (9.0 pts),Question 10 (10.0 pts),Question 11 (4.0 pts),Question 12 (7.0 pts)
0,A99432453,3.0,6.0,8.0,5.0,5.0,6.0,4.0,3.0,4.0,4.0,4.0,4.0
1,A99152420,5.0,6.0,8.0,5.0,10.0,6.0,9.0,6.0,4.0,10.0,4.0,5.0
2,A99892710,3.0,5.0,8.0,4.0,4.0,5.0,3.0,6.0,9.0,9.0,4.0,7.0
3,A99381181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A99990217,4.0,6.0,8.0,6.0,7.0,6.0,7.0,5.0,9.0,4.0,4.0,7.0

Note that `final_breakdown` has the same number of rows as `grades`, but a different number of columns:

In [32]:
final_breakdown.shape

(535, 13)

Also note that student `'A99381181'` has a score of `NaN` for each question because they did not take the final exam:

In [33]:
grades.loc[grades['PID'] == 'A99381181', 'Final']

86   NaN
Name: Final, dtype: float64

### Question 8

([return to the outline](#Navigating-the-Project))

Let's get started.

#### `raw_redemption`

Complete the implementation of the function `raw_redemption`, which takes in a DataFrame like `final_breakdown` and a list of integers, corresponding to the question numbers for "redemption questions." The function should return a DataFrame with two columns:
- `'PID'`, the PID for each student in `final_breakdown`.
- `'Raw Redemption Score'`, which is the proportion of points each student earned, when only considering redemption questions.

For example, suppose `example_breakdown` is as follows:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>PID</th>
      <th>Question 1 (6.0 pts)</th>
      <th>Question 2 (3.0 pts)</th>
      <th>Question 3 (1.0 pts)</th>
      <th>Question 4 (4.5 pts)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>A99706914</td>
      <td>6</td>
      <td>3</td>
      <td>1</td>
      <td>4.5</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A99237411</td>
      <td>2</td>
      <td>0</td>
      <td>1</td>
      <td>4.5</td>
    </tr>
    <tr>
      <th>2</th>
      <td>A99489712</td>
      <td>4</td>
      <td>1</td>
      <td>0</td>
      <td>4.0</td>
    </tr>
  </tbody>
</table>

`raw_redemption(example_breakdown, [1, 3])` should return the following DataFrame:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>PID</th>
      <th>Raw Redemption Score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>A99706914</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A99237411</td>
      <td>0.428571</td>
    </tr>
    <tr>
      <th>2</th>
      <td>A99489712</td>
      <td>0.571429</td>
    </tr>
  </tbody>
</table>



***Notes***:
- **Assume that for each question in `final_breakdown`, at least one student received a perfect score.**
- Assume that the input DataFrame will be in the same format as `final_breakdown`, in that the column at position 0 will be labeled `'PID'`, the column at position 1 will contain scores for Question 1, the column at position 2 will contain scores for Question 2, and so on.
- If a student didn't take the final, their raw redemption score should be 0.
- Again, do not round.

<br>

#### `combine_grades`

Then, complete the implementation of the function `combine_grades`, which takes in a DataFrame like `grades` and a DataFrame like the one returned by `raw_redemption`. The function should return a new DataFrame with all the columns from `grades`, plus a new column labelled `'Raw Redemption Score'` which contains the raw redemption score for each student.

***Hint***: We cannot directly add the `'Raw Redemption Score'` from the redemption DataFrame to the `grades` DataFrame, as the `'PID'` columns in the two DataFrames won't necessarily match.

In [89]:
def raw_redemption(dFrame, rQuestions):
    dFrame = dFrame.fillna(0)
    each_question = []
    for i in rQuestions:
        each_question.append(dFrame.get(dFrame.columns[i]))
    max_scores = []
    for i in each_question:
        max_scores.append(np.max(i))
    raw_redemption_scores = np.zeros(len(each_question[0]))
    for series in each_question:
        for index in range(len(series)):
            raw_redemption_scores[index] += series[index]
    return_dFrame = dFrame
    return_dFrame["Raw Redemption Score"] = raw_redemption_scores / sum(max_scores)
    return_dFrame = return_dFrame.set_index("PID").get("Raw Redemption Score")
    return pd.DataFrame(return_dFrame).reset_index()

In [90]:
def combine_grades(grades, raw_redemption):
    return grades.merge(raw_redemption, on="PID", how="left")

In [91]:
raw_redemption(final_breakdown, [1, 2, 8, 9, 6])

           PID  Raw Redemption Score
0    A99432453               0.68750
1    A99152420               0.84375
2    A99892710               0.87500
3    A99381181               0.00000
4    A99990217               0.93750
..         ...                   ...
530  A99190272               1.00000
531  A99330622               0.90625
532  A99152694               0.75000
533  A99174029               0.65625
534  A99043621               1.00000

[535 rows x 2 columns]

In [92]:
grader.check("q8")

q8 results: All test cases passed!

For our particular offering of CSD 18, the redemption questions on the final exam were Questions 1, 2, 3, 7, 9, and 12. Run the cell below to define a new DataFrame named `grades_combined` that results from calling the above two functions on grades from this class.

In [93]:
grades_combined = combine_grades(grades, raw_redemption(final_breakdown, [1, 2, 3, 7, 9, 12]))
grades_combined

,PID,College,Level,Section,lab01,lab01 - Max Points,lab01 - Lateness (H:M:S),lab02,lab02 - Max Points,lab02 - Lateness (H:M:S),...,discussion08,discussion08 - Max Points,discussion08 - Lateness (H:M:S),discussion09,discussion09 - Max Points,discussion09 - Lateness (H:M:S),discussion10,discussion10 - Max Points,discussion10 - Lateness (H:M:S),Raw Redemption Score
0,A99706914,ERC,JR,A22,99.735279,100.0,00:00:00,84.990171,100.0,00:00:00,...,8.895294,10,00:00:00,10.000000,10,780:01:28,10.000000,10,00:00:00,0.844444
1,A99237411,Eighth,JR,A29,98.829476,100.0,00:00:00,50.784231,100.0,00:00:00,...,9.022407,10,00:00:00,9.020283,10,00:00:00,9.437368,10,00:00:00,0.866667
2,A99690544,Revelle,SR,A12,86.513369,100.0,00:00:00,47.802820,100.0,00:00:00,...,3.030538,10,00:04:51,7.613698,10,00:00:00,9.624617,10,00:00:00,0.777778
3,A99427381,Seventh,JR,A14,100.000000,100.0,00:00:00,100.000000,100.0,00:00:00,...,10.000000,10,00:00:00,9.249126,10,00:00:00,10.000000,10,00:00:00,0.888889
4,A99489712,Sixth,JR,A24,66.506974,100.0,00:00:00,33.422412,100.0,00:00:00,...,4.439606,10,00:00:00,4.485291,10,00:00:00,6.282712,10,00:00:00,0.822222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530,A99073025,Warren,JR,A12,100.000000,100.0,47:26:10,82.022753,100.0,00:00:00,...,10.000000,10,12:08:58,9.169447,10,00:00:00,10.000000,10,00:00:00,0.755556
531,A99257552,Warren,SO,A02,100.000000,100.0,00:00:00,87.498073,100.0,00:00:00,...,10.000000,10,00:00:00,10.000000,10,00:00:00,10.000000,10,00:00:00,0.800000
532,A99592629,Revelle,JR,A15,88.656641,100.0,00:00:00,90.326041,100.0,00:00:00,...,9.878661,10,00:00:00,8.878946,10,00:00:00,10.000000,10,00:00:00,0.711111
533,A99033808,Seventh,SR,A13,83.799719,100.0,00:00:00,85.636947,100.0,00:00:00,...,7.759434,10,00:00:00,8.655478,10,419:06:41,8.102277,10,00:00:00,0.866667
534,A99855328,Seventh,SR,A01,88.389331,100.0,00:00:00,73.045171,100.0,00:00:00,...,10.000000,10,00:00:00,9.515494,10,00:00:00,10.000000,10,00:00:00,0.955556

### Question 9

([return to the outline](#Navigating-the-Project))

Now that we have all of our information about each student in one DataFrame, we can compute their z-score on both the original midterm exam and the redemption questions on the final exam.

#### `z_score`

Complete the implementation of the function `z_score`, which takes in a Series of numbers and returns a Series in which all elements are converted to z-scores. As a reminder, to convert a sequence of numbers to z-scores, or standard units, we use the following formula:

$$z(x_i) = \frac{x_i - \text{mean of } x}{\text{SD of }x}$$

***Notes***:

- Make sure to set the `ddof=0` in whichever method or function you use to compute standard deviation. `numpy` and `pandas` both use different default denominators when computing standard deviation. (`ddof=0` computes the "population" standard deviation and `ddof=1` computes the "sample" standard deviation.)
- Do **not** fill null values – that is, if a value in the input Series is `NaN`, its value in the output Series should also be `NaN`. (Depending on how you implement `z_score`, this may happen automatically.)
    - Address null midterm scores in `add_post_redemption`, not `z_score`.

<br>

#### `add_post_redemption`

Complete the implementation of the function `add_post_redemption`, which takes in a DataFrame like `grades_combined` and returns a DataFrame with all the columns from `grades_combined` in addition to two new columns:
- `'Midterm Score Pre-Redemption'`, which contains each student's midterm exam score as a proportion between 0 and 1 **before** redemption.
- `'Midterm Score Post-Redemption'`, which containing each student's midterm exam score **after** the redemption policy has been applied, again as a proportion between 0 and 1.

You can use your `z_score` function to compute the z-scores of each student's original midterm exam grades and raw redemption scores. **Note that there are students who didn't take the midterm; such students need to have their `NaN` scores fixed prior to calculating their pre-redemption z-scores**, otherwise, you may end up incorrectly giving them `NaN` post-redemption midterm scores. None of the redemption z-scores should be `NaN`, since you handled null values in your implementation of `raw_redemption`.

If it's not clear, **computing the `'Midterm Score Post-Redemption'` column is the most complicated part of this question**. Make sure you understand how the redemption policy for CSD 18 works before approaching this question. If you need to refresh your understanding, re-read the instructions at the start of [Part 2](#part2).

In [94]:
def z_score(series):
    series_std = series.std(ddof=0)
    series_mean = np.mean(series)
    return (series - series_mean) / series_std

In [95]:
def add_post_redemption(df):
    # Since her redemption z-score, $0.8485$, is greater than her midterm z-score, $0.6286$, her midterm exam score of $\frac{53}{70} \approx 0.7571$ will be replaced with
    #v $$\text{Jasmine's redemption z-score} \cdot \text{class' midterm SD} + \text{class' midterm mean} \approx 0.8485 \cdot 0.25 + 0.6 = \boxed{0.8121}$$
    original_zscore = z_score(df["Midterm"])
    redemption_zscore = z_score(df["Raw Redemption Score"])
    updated_scores = []
    for index in range(len(redemption_zscore)):
        if redemption_zscore[index] > original_zscore[index]:
            updated_scores.append(redemption_zscore.iloc[index] * (df["Midterm"]).std(ddof=0) + np.mean(df["Midterm"]))
        else:
            updated_scores.append(df["Midterm"][index])
    df["Midterm Score Pre-Redemption"] = df["Midterm"] / df["Midterm - Max Points"]
    df["Midterm Score Post-Redemption"] = updated_scores / df["Midterm - Max Points"]
    return df

In [96]:
z_score(grades["Midterm"])
add_post_redemption(grades_combined)

,PID,College,Level,Section,lab01,lab01 - Max Points,lab01 - Lateness (H:M:S),lab02,lab02 - Max Points,lab02 - Lateness (H:M:S),...,discussion08 - Lateness (H:M:S),discussion09,discussion09 - Max Points,discussion09 - Lateness (H:M:S),discussion10,discussion10 - Max Points,discussion10 - Lateness (H:M:S),Raw Redemption Score,Midterm Score Pre-Redemption,Midterm Score Post-Redemption
0,A99706914,ERC,JR,A22,99.735279,100.0,00:00:00,84.990171,100.0,00:00:00,...,00:00:00,10.000000,10,780:01:28,10.000000,10,00:00:00,0.844444,1.000000,1.000000
1,A99237411,Eighth,JR,A29,98.829476,100.0,00:00:00,50.784231,100.0,00:00:00,...,00:00:00,9.020283,10,00:00:00,9.437368,10,00:00:00,0.866667,0.912166,0.912166
2,A99690544,Revelle,SR,A12,86.513369,100.0,00:00:00,47.802820,100.0,00:00:00,...,00:04:51,7.613698,10,00:00:00,9.624617,10,00:00:00,0.777778,0.804012,0.804012
3,A99427381,Seventh,JR,A14,100.000000,100.0,00:00:00,100.000000,100.0,00:00:00,...,00:00:00,9.249126,10,00:00:00,10.000000,10,00:00:00,0.888889,0.947108,0.947108
4,A99489712,Sixth,JR,A24,66.506974,100.0,00:00:00,33.422412,100.0,00:00:00,...,00:00:00,4.485291,10,00:00:00,6.282712,10,00:00:00,0.822222,0.416396,0.837158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530,A99073025,Warren,JR,A12,100.000000,100.0,47:26:10,82.022753,100.0,00:00:00,...,12:08:58,9.169447,10,00:00:00,10.000000,10,00:00:00,0.755556,0.882106,0.882106
531,A99257552,Warren,SO,A02,100.000000,100.0,00:00:00,87.498073,100.0,00:00:00,...,00:00:00,10.000000,10,00:00:00,10.000000,10,00:00:00,0.800000,0.537590,0.816615
532,A99592629,Revelle,JR,A15,88.656641,100.0,00:00:00,90.326041,100.0,00:00:00,...,00:00:00,8.878946,10,00:00:00,10.000000,10,00:00:00,0.711111,0.880445,0.880445
533,A99033808,Seventh,SR,A13,83.799719,100.0,00:00:00,85.636947,100.0,00:00:00,...,00:00:00,8.655478,10,419:06:41,8.102277,10,00:00:00,0.866667,1.000000,1.000000
534,A99855328,Seventh,SR,A01,88.389331,100.0,00:00:00,73.045171,100.0,00:00:00,...,00:00:00,9.515494,10,00:00:00,10.000000,10,00:00:00,0.955556,0.811584,0.960417

In [97]:
grader.check("q9")

q9 results: All test cases passed!

### Question 10

([return to the outline](#Navigating-the-Project))

Now, we're equipped to re-compute each student's course grade after the redemption policy.

#### `total_points_post_redemption`

Complete the implementation of the function `total_points_post_redemption`, which takes in a DataFrame like `grades_combined` and returns a Series containing each student's course grade after redemption. As a refresher, **course grades should be proportions between 0 and 1.**

You should not have to repeat any of your calculations for assignments other than the midterm exam – use your output from `total_points` and adjust it. Remember that, per [the syllabus](#The-Syllabus), the midterm exam is worth 15%.

<br>

#### `proportion_improved`

Finally, complete the implementation of the function `proportion_improved`, which takes in a DataFrame like `grades_combined` and returns the **proportion of students in the class whose letter grade increased** due to the redemption policy.

***Hints***:
- If you've implemented everything correctly, `proportion_improved(grades_combined)` should evaluate to a proportion between 0.07 and 0.12.
- Remember, it is impossible for a student's letter grade to decrease due to the redemption policy.

In [98]:
def total_points_post_redemption(df):
    df = df.fillna(0)
    return pd.Series(total_points(df) - (df["Midterm Score Pre-Redemption"] * 0.15) + (df["Midterm Score Post-Redemption"] * 0.15))

In [99]:
def proportion_improved(df):
    adjusted_scores = total_points_post_redemption(df)
    original_scores = total_points(df)
    count = 0
    adjusted_individual = final_grades(adjusted_scores)
    original_individual = final_grades(original_scores)
    for i in range(len(adjusted_individual)):
        if adjusted_individual[i] < original_individual[i]:
            count += 1
    return count / len(adjusted_individual)

In [100]:
total_points_post_redemption(grades_combined)
proportion_improved(grades_combined)

0.10841121495327102

In [101]:
grader.check("q10")

q10 results: All test cases passed!

Great! Thanks to your implementation of the redemption policy, a sizeable fraction of CSD 18 students saw their letter grades improve.

<a name='part3'></a>

## Part 3: Analysis 🧠

([return to the outline](#Navigating-the-Project))


Now that we have students' letter grades before and after redemption, it's time to analyze how the class performed overall. First, because we're going to use them frequently in this part, we'll add a few extra columns to `grades_combined` and call the resulting DataFrame `grades_analysis`.

In [102]:
grades_analysis = grades_combined.assign(**{
    'Total Points Pre-Redemption': total_points(grades_combined),
    'Letter Grade Pre-Redemption': final_grades(total_points(grades_combined)),
    'Total Points Post-Redemption': total_points_post_redemption(grades_combined),
    'Letter Grade Post-Redemption': final_grades(total_points_post_redemption(grades_combined))
})
grades_analysis.head()

,PID,College,Level,Section,lab01,lab01 - Max Points,lab01 - Lateness (H:M:S),lab02,lab02 - Max Points,lab02 - Lateness (H:M:S),...,discussion10,discussion10 - Max Points,discussion10 - Lateness (H:M:S),Raw Redemption Score,Midterm Score Pre-Redemption,Midterm Score Post-Redemption,Total Points Pre-Redemption,Letter Grade Pre-Redemption,Total Points Post-Redemption,Letter Grade Post-Redemption
0,A99706914,ERC,JR,A22,99.735279,100.0,00:00:00,84.990171,100.0,00:00:00,...,10.000000,10,00:00:00,0.844444,1.000000,1.000000,0.902389,A,0.902389,A
1,A99237411,Eighth,JR,A29,98.829476,100.0,00:00:00,50.784231,100.0,00:00:00,...,9.437368,10,00:00:00,0.866667,0.912166,0.912166,0.816924,B,0.816924,B
2,A99690544,Revelle,SR,A12,86.513369,100.0,00:00:00,47.802820,100.0,00:00:00,...,9.624617,10,00:00:00,0.777778,0.804012,0.804012,0.759308,C,0.759308,C
3,A99427381,Seventh,JR,A14,100.000000,100.0,00:00:00,100.000000,100.0,00:00:00,...,10.000000,10,00:00:00,0.888889,0.947108,0.947108,0.908499,A,0.908499,A
4,A99489712,Sixth,JR,A24,66.506974,100.0,00:00:00,33.422412,100.0,00:00:00,...,6.282712,10,00:00:00,0.822222,0.416396,0.837158,0.674545,D,0.737659,C

You may have noticed that `grades_analysis` has a `'Section'` column that we haven't yet touched. There are 30 unique values in the `'Section'` column – `'A01'`, `'A02'`, ..., `'A30'`, corresponding to the 30 different discussion sections the students CSD 18 were enrolled in. Discussion sections and discussion assignments have nothing to do with one another, for the purposes of calculating grades, and moving forward, we'll refer to these just as "sections."

In [103]:
grades_analysis['Section'].nunique()

30

In [104]:
grades_analysis['Section'].unique()

array(['A22', 'A29', 'A12', 'A14', 'A24', 'A23', 'A01', 'A06', 'A11',
       'A28', 'A27', 'A04', 'A02', 'A18', 'A17', 'A15', 'A30', 'A16',
       'A13', 'A08', 'A26', 'A05', 'A21', 'A03', 'A19', 'A07', 'A25',
       'A10', 'A09', 'A20'], dtype=object)

Much of our analysis in this part will pertain to how students in different sections performed in CSD 18.

### Question 11

([return to the outline](#Navigating-the-Project))

#### `section_most_improved`

Complete the implementation of the function `section_most_improved`, which takes in a DataFrame like `grades_analysis` and returns the section in which **the greatest proportion of students had their letter grades increase due to the redemption policy**. For example, if 48\% of students in section `'A25'` had their letter grades increase due to the redemption policy, and no other section had more than 48\% of students increase, then `section_most_improved` should return `'A25'`. 

If there is a tie, return any one of the sections.

<br>

#### `top_sections`

Complete the implementation of the function `top_sections`, which takes in a DataFrame like `grades_analysis`, a float `t` between 0 and 1, and an integer `n`, and returns **an array containing the sections in which at least `n` students earned a raw score of at least `t` on the final exam**. The section names in the returned array should be sorted in alphanumeric order.

For example, `top_sections(grades_analysis, 0.75, 10)` should return an array of the sections in which at least 10 students scored at least 75% on the final exam.

In [105]:
def section_most_improved(df):
    return df[["Section", "Total Points Post-Redemption"]].groupby("Section")["Total Points Post-Redemption"].mean().sort_values(ascending=False).index[0]

In [106]:
def top_sections(df, t, n):
    df = df[df["Final"] >= t]
    valid_sections = (df["Section"].value_counts() >= n) 
    valid_sections = valid_sections[valid_sections == True].index
    return np.sort(valid_sections.to_numpy())

In [107]:
section_most_improved(grades_analysis)
top_sections(grades_analysis, 0.75, 10)

array(['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09',
       'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18',
       'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27',
       'A28', 'A29', 'A30'], dtype=object)

In [108]:
grader.check("q11")

q11 results: All test cases passed!

### Question 12

([return to the outline](#Navigating-the-Project))

Complete the implementation of the function `rank_by_section`, which takes in a DataFrame like `grades_analysis` and returns a DataFrame describing **students' _ranks_ based on total points (post-redemption) for each section**.

Specifically, the DataFrame should have `n` rows that describe the rank – indexed `1`, `2`, ..., `n` (where `n` is the number of students in the largest section), in that order – and 30 columns – `'A01'`, `'A02'`, ..., `'A30'`, in that order. **The entry in row `r` and column `s` should correspond to the PID of the student who had the `r`th most total points in section `s`, after redemption.** For sections that have fewer than `n` students, fill the extra entries in those columns with **empty strings**. There might exist ties for students with total points of 0.

For instance, suppose there were only four sections, and the largest section had five students. The DataFrame returned by `rank_by_section` might look like:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Section</th>
      <th>A01</th>
      <th>A02</th>
      <th>A03</th>
      <th>A04</th>
    </tr>
    <tr>
      <th>Section Rank</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>A99404117</td>
      <td>A99318825</td>
      <td>A99093358</td>
      <td>A99339719</td>
    </tr>
    <tr>
      <th>2</th>
      <td>A99477753</td>
      <td>A99396913</td>
      <td>A99933171</td>
      <td>A99082089</td>
    </tr>
    <tr>
      <th>3</th>
      <td></td>
      <td>A99159214</td>
      <td>A99164028</td>
      <td>A99950565</td>
    </tr>
    <tr>
      <th>4</th>
      <td></td>
      <td>A99322859</td>
      <td></td>
      <td>A99715029</td>
    </tr>
    <tr>
      <th>5</th>
      <td></td>
      <td>A99739120</td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

Note that the PIDs in your DataFrame will be different than those above; also note that your DataFrame may have a different string where the example has `'Section Rank'`, and that's fine.

***Hints***: 
- Our solution used `groupby` with a helper function, and then `pivot` on the result. This is a tricky problem – work through it one step at a time.

- Try to use `.sort_values` rather than `.rank` in this question. This is because ties are assigned the mean of the ranks of the ties by default if you use `.rank`. For more information, please refer to `.rank` [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rank.html).

In [109]:
def rank_by_section(df):
    num_rows = df.groupby(["Section"]).count()["PID"].max()
    sections = list(df.groupby("Section").count().reset_index()["Section"])
    new_df = pd.DataFrame(index=range(num_rows), columns=sections)
    for section in sections:
        short_list = list(df.groupby(["Section", "PID"]).sum().loc[section].sort_values("Total Points Post-Redemption", ascending=False).reset_index()["PID"])
        short_list += [None] * (num_rows - len(short_list))
        new_df[section] = short_list
    return new_df.fillna("")

In [110]:
rank_by_section(grades_analysis)

,A01,A02,A03,A04,A05,A06,A07,A08,A09,A10,...,A21,A22,A23,A24,A25,A26,A27,A28,A29,A30
0,A99554279,A99434139,A99433693,A99187571,A99005866,A99861848,A99465192,A99822771,A99642988,A99906367,...,A99918730,A99154676,A99488919,A99725232,A99976381,A99241737,A99101160,A99268867,A99797507,A99200920
1,A99729300,A99768653,A99681733,A99464434,A99058806,A99351423,A99401601,A99005516,A99361565,A99612659,...,A99420529,A99583699,A99688028,A99264628,A99425689,A99718695,A99524149,A99449376,A99743631,A99234372
2,A99855328,A99323314,A99307531,A99755345,A99684231,A99185365,A99142019,A99667178,A99177000,A99601330,...,A99477620,A99733449,A99784236,A99692599,A99471668,A99673095,A99704673,A99491048,A99787562,A99314573
3,A99765989,A99267806,A99776300,A99853966,A99445386,A99860066,A99964440,A99150572,A99732298,A99860540,...,A99841774,A99962240,A99302544,A99434027,A99663899,A99630726,A99336610,A99544353,A99156002,A99016583
4,A99705260,A99293363,A99761150,A99523249,A99803382,A99278317,A99659024,A99650853,A99337484,A99408920,...,A99999789,A99146887,A99043621,A99326575,A99678684,A99772423,A99241375,A99930150,A99230041,A99644077
5,A99592218,A99479714,A99215099,A99733996,A99073327,A99699336,A99919922,A99789220,A99985911,A99399192,...,A99804308,A99329157,A99695471,A99591842,A99461345,A99075184,A99587120,A99589329,A99645522,A99437421
6,A99871576,A99787420,A99717448,A99324445,A99747684,A99509446,A99368334,A99659593,A99374440,A99780069,...,A99966530,A99706914,A99955501,A99121073,A99120173,A99853534,A99254768,A99243568,A99928159,A99713530
7,A99354806,A99903355,A99139365,A99213547,A99213370,A99797850,A99442125,A99674390,A99400672,A99813051,...,A99955905,A99214049,A99314089,A99440253,A99991623,A99712347,A99699554,A99812803,A99166536,A99675787
8,A99926792,A99754970,A99024616,A99720730,A99745325,A99431965,A99828360,A99675706,A99604013,A99220904,...,A99516490,A99177632,A99288102,A99949176,A99199917,A99599711,A99087453,A99811275,A99313805,A99895917
9,A99293130,A99108785,A99975877,A99354539,A99856997,A99681640,A99427118,A99846618,A99622715,A99392053,...,A99501183,A99149643,A99447514,A99531845,A99873132,A99970560,A99985778,A99470227,A99614172,A99291854
10,A99198021,A99565442,A99764895,A99453518,A99512204,A99803516,A99422088,A99721450,A99060338,A99282192,...,A99631742,A99671971,A99703408,A99033883,A99902897,A99474493,A99505703,A99657248,A99320977,A99832436
11,A99217669,A99152955,A99725519,A99407199,A99305019,A99413193,A99538160,A99556503,A99044599,A99279088,...,A99631007,A99821878,A99076268,A99653302,A99133973,A99622000,A99709028,A99950620,A99903882,A99077511
12,A99016187,A99955246,A99744857,A99541515,,A99514650,A99483063,A99260191,,A99773945,...,A99078383,A99895960,A99276731,A99489712,A99319569,A99305717,A99509569,A99610080,A99059458,A99051778
13,A99916894,A99381333,A99694766,A99833850,,A99492512,A99084758,A99170745,,A99835919,...,,A99379415,A99583638,A99547146,A99570934,A99656504,A99800662,A99071510,A99237411,A99856175
14,A99600940,A99925394,A99615956,A99856805,,A99229067,,A99054168,,A99409352,...,,A99600090,A99678484,,A99275005,A99226067,A99277895,A99467073,A99330622,A99589063
15,A99592712,A99257552,A99006199,A99156116,,A99922626,,A99336438,,A99384291,...,,A99285068,A99266984,,A99230637,A99625175,,A99436409,A99994501,A99892710
16,A99741577,A99290566,,A99963271,,A99661343,,,,A99441989,...,,A99339034,A99747041,,A99432920,A99532389,,,A99503277,A99542346
17,A99174029,,,A99269295,,A99734921,,,,A99714021,...,,A99055110,A99340665,,A99995615,,,,A99943708,A99954694
18,A99668602,,,A99244880,,A99616529,,,,A99485341,...,,A99941362,A99222775,,A99676635,,,,A99505023,A99581496
19,,,,,,A99392943,,,,A99573583,...,,A99777720,A99356598,,A99989846,,,,A99871763,
20,,,,,,,,,,A99997380,...,,,A99596327,,A99669980,,,,,
21,,,,,,,,,,A99571242,...,,,A99611845,,A99272538,,,,,
22,,,,,,,,,,A99090510,...,,,A99218475,,A99437369,,,,,
23,,,,,,,,,,A99001164,...,,,A99177849,,,,,,,
24,,,,,,,,,,,...,,,A99850135,,,,,,,
25,,,,,,,,,,,...,,,A99381181,,,,,,,

In [111]:
grader.check("q12")

q12 results: All test cases passed!

### Question 13

([return to the outline](#Navigating-the-Project))

To wrap up, let's _visualize_ how the students in each section of CSD 18 performed.

Complete the implementation of the function `letter_grade_heat_map`, which takes in a DataFrame like `grades_analysis` and returns a `plotly` figure object containing a heatmap describing **the distribution of letter grades (post-redemption) for each section**.

Specifically, the heatmap should have 5 rows – `'A'`, `'B'`, `'C'`, `'D'`, and `'F'`, in that order – and 30 columns – `'A01'`, `'A02'`, ..., `'A30'`, in that order. **The color of the square in row `g` and column `s` should correspond to the proportion of students in section `s` who earned a letter grade (post-redemption) of `g`.**

To create your figure, you'll use the `px.imshow` function and provide several arguments. This [`plotly` article](https://plotly.com/python/imshow/) will be extremely helpful.

Here are some additional requirements to get full credit for your heatmap:
- Set the color scale to be something other than the default. Note that in this heatmap, you should use a sequential color scheme, which means that the intensity of the color assigned to a square is proportional to the value being plotted for that square (e.g. darker colors should correspond to larger proportions and lighter colors should correspond to smaller proportions, or vice versa). Read more about the theory of sequential and diverging color schemes [here](https://blog.datawrapper.de/diverging-vs-sequential-color-scales/).
- Set the title of the plot to `'Distribution of Letter Grades by Section'`.

An example plot that satisfies all of these conditions is shown below, though we encourage you to customize yours within the confines above. Can you change the font?

<img src="data/heatmap-example.png" width=100%>

It's fine if your x-axis labels are rotated.

Remember to return the figure object itself. That is, somewhere in your code you will have `fig = px.imshow(...)`; make sure to also `return fig`.

***Hint***: Most of the work in this question is creating the DataFrame to call `px.imshow` on.

In [112]:
def letter_grade_heat_map(df):
    sections = np.sort(df["Section"].unique())
    props = []
    for section in sections:
        current_section = df[df["Section"] == section]
        props.append(letter_proportions(current_section["Total Points Post-Redemption"]).sort_index())
    props = pd.DataFrame(props).T
    fig = px.imshow(props, labels=dict(x="Section", y="Letter Grades"),
                x=sections,
                y=['A', 'B', 'C', 'D', 'F'],
                color_continuous_scale='tempo')
    fig.update_layout(title="Distribution of Letter Grades by Section", font=dict(size=20))
    fig.update_layout(
    xaxis_title_font=dict(size=20),
    yaxis_title_font=dict(size=20)
    )
    return fig

In [113]:
letter_grade_heat_map(grades_analysis)

Run the cell below to see your heatmap.

In [114]:
# Run this cell to see the result, and don't change this cell --- it is needed for the tests.
fig = letter_grade_heat_map(grades_analysis)
fig.show()

In [115]:
grader.check("q13")

q13 results: All test cases passed!

## Congratulations, you've finished Project 1! 🎉

As a reminder, all of the work you want to submit needs to be in `project.py` – this notebook should not be uploaded because there are no manually-graded questions in this project.

To ensure that all of the work you want to submit is in `project.py`, we've included a script named `project-validation.py` in the project folder. You shouldn't edit it, but instead, you should call it from the command line (e.g. the Terminal) to test your work.

Once you've finished the project, you should open the command line and run, in the directory for this project:

```
python project-validation.py
```

**This will run all of the `grader.check` cells that you see in this notebook, but only using the code in `project.py` – that is, it doesn't look at any of the code in this notebook. If all of your `grader.check` cells pass in this notebook but not all of them pass in your command line with the above command, then you likely have code in your notebook that isn't in your `project.py`!**

You can also use `project-validation.py` to test individual questions. For instance,

```
python project-validation.py q1 q4 q7 q8
```

will run the `grader.check` cells for Questions 1, 4, 7, and 8 – again, only using the code in `project.py`.

Once `python project-validation.py` shows that you're passing all test cases, you're ready to submit your `project.py` (and only your `project.py`) to Gradescope. Once submitting to Gradescope, make sure to stick around until all test cases pass.

There is also a call to `grader.check_all()` below in _this_ notebook, but make sure to also follow the steps above.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [116]:
grader.check_all()

q1 results: All test cases passed!

q10 results: All test cases passed!

q11 results: All test cases passed!

q12 results: All test cases passed!

q13 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!

q4 results: All test cases passed!

q5 results: All test cases passed!

q6 results: All test cases passed!

q7 results: All test cases passed!

q8 results: All test cases passed!

q9 results: All test cases passed!